*&---------------------------------------------------------------------*
*& Include          Z15W_EX_ASSIGNMENT_001_SEL
*&---------------------------------------------------------------------*

* UPLOAD 파일
SELECTION-SCREEN BEGIN OF BLOCK BL01 WITH FRAME TITLE TEXT-001.
    PARAMETERS: P_FILE TYPE RLGRAP-FILENAME DEFAULT 'C:\' OBLIGATORY.
SELECTION-SCREEN END OF BLOCK BL01.
SELECTION-SCREEN BEGIN OF BLOCK BL02 WITH FRAME TITLE TEXT-002.
PARAMETERS: r1 RADIOBUTTON GROUP rad DEFAULT 'X',
            r2 RADIOBUTTON GROUP rad,
            r3 RADIOBUTTON GROUP rad.
SELECTION-SCREEN END OF BLOCK BL02.
* FUNCTION KEY
SELECTION-SCREEN: FUNCTION KEY 1.
SELECTION-SCREEN: FUNCTION KEY 3.
*** INCLUDE Z22W_EX_ZSTRVELAG_001_SEL
*** INCLUDE Z22W_EX_ZSTRVELAG_001_SEL
